### ISSUE TITLE
no locale

### ISSUE THREAD

**Issue by No4NaMe** [MichaelBelgium/flarum-profile-views#1]
no locale AddAssets.php
/**
@param ConfigureLocales $event
/
public function configLocales(ConfigureLocales $event)
{
$event->locales->addTranslations('en', DIR.'/../../locale/en.yml');
}
}

**Comment by MichaelBelgium** [comment]
If you mean there's no support for other languages, it's fixed in 2fec6d6e879a068b6854fb23f442bb344716b04a
